spin_manifest_version = 2

[application]
authors = ["Christian Weyer <cw@thinktecture.com>"]
description = ""
name = "dotnet-spin-http"
version = "1.0.0"

[[trigger.http]]
route = "/..."
component = "dotnet-spin-http"

[component.dotnet-spin-http]
source = "bin/Release/net8.0/DotnetSpinHttp.wasm"
[component.dotnet-spin-http.build]
command = "dotnet build -c Release"
